server.port=${PORT:8080}
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.datasource.url=jdbc:h2:mem:appdb;MODE=MySQL;DB_CLOSE_DELAY=-1;SCHEMA=PUBLIC
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=PUBLIC
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.mustache.check-template-location=false
vaadin.launch-browser=true
logging.level.root=INFO
logging.level.de.derpeterson.app=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.atmosphere=INFO
logging.level.com.vaadin=INFO
logging.level.com.vaadin.flow=INFO
logging.level.org.springframework.boot.autoconfigure.orm.jpa=ERROR