"""Generate model commands and remove stale commands owned by this generator."""
import json
import re
from pathlib import Path

MARKER = "<!-- GENERATED BY generate_start_commands.py - DO NOT EDIT -->"


def generate(root: Path) -> int:
    entries = json.loads((root / "benchmark-models.json").read_text(encoding="utf-8-sig"))["models"]
    if not entries:
        raise ValueError("No models configured.")
    commands = root / "commands"
    planned = {}
    for entry in entries:
        key = entry.get("command", "")
        if not re.fullmatch(r"[a-z0-9]+(?:[.-][a-z0-9]+)*", key) or key in planned:
            raise ValueError(f"Invalid/duplicate model command: {key}")
        if not entry.get("name") or not entry.get("provider") or entry.get("mode") not in ("forced", "selected"):
            raise ValueError("Every model needs name, provider and selected/forced mode.")
        if entry["mode"] == "forced" and not entry.get("model"):
            raise ValueError("Forced model requires a model ID.")
        path = commands / ("start-" + key + ".md")
        if path.exists() and MARKER not in path.read_text(encoding="utf-8-sig"):
            raise ValueError(f"Refusing to overwrite manual command {path}")
        header = ["---", "description: " + json.dumps("Start workflow with " + entry["name"]), "subtask: false"]
        if entry["mode"] == "forced":
            header += ["model: " + json.dumps(entry["model"])]
        header += ["---", "", MARKER, ""]
        body = [f"Model catalog key: `{key}`. Provider label: {entry['provider']}.",
                "This wrapper uses the complete workflow in `.opencode/commands/start.md`.",
                "Read that file and execute its steps using actual tools.", "",
                "Input: $ARGUMENTS", "",
                f"Syntax: `/start-{key} <modules> <branch|-> <targetClass|-> <complete task>`",
                "Split input at most three times. Preserve the entire remaining task.",
                f"Insert `{key}` as the fourth token for the generic /start parsing;",
                "never run task text as shell code."]
        body += ([f"This command forces `{entry['model']}` through model frontmatter."] if entry["mode"] == "forced"
                 else [f"This command preserves the selected model. The user must visibly select {entry['name']} first."])
        planned[key] = (path, "\n".join(header + body) + "\n")
    stale = [path for path in commands.glob("start-*.md") if MARKER in path.read_text(encoding="utf-8-sig")
             and path not in {pair[0] for pair in planned.values()}]
    # Validate every destination before any mutation. Never delete manual commands.
    commands.mkdir(parents=True, exist_ok=True)
    for path, content in planned.values():
        path.write_text(content, encoding="utf-8")
    for path in stale:
        path.unlink()
    return len(planned)


if __name__ == "__main__":
    print(f"Generated {generate(Path(__file__).resolve().parents[1])} start model commands.")
